### ISSUE TITLE
Assets in project markdown resolved with wrong base URL

### ISSUE THREAD

**Issue by manniL** [unjs/website#4]
Hey! Image assets of project markdown are resolved wrongly.

# Reproduction

1. Go to https://unjs.io/webpackbar
2. See the logo is resolved as "https://unjs.io/assets/logo.svg", in original repo as "https://github.com/unjs/webpackbar/raw/main/assets/logo.svg"

**Comment by serkodev** [comment]
Please check PR #14 that fix this issue.

**Comment by serkodev** [comment]
Regarding to the latest commit https://github.com/unjs/website/commit/28f8135461f3f97912f5504faa8bae5c1f5c7a6d there are still some bugs are not being resolve.

1. The `<a> href` links are still not resolved.
e.g. `./assets/logo.svg` still linking to `https://unjs.io/assets/logo.svg`

2. If the URL starting with `src="asset` instead of `src="./asset/"`, it cannot replace with the regex `/src="\./g`

Sample: https://unjs.io/webpackbar

Hope to continue the discussion in PR #12 possible.

**Comment by serkodev** [comment]
Regarding to the latest commit https://github.com/unjs/website/commit/28f8135461f3f97912f5504faa8bae5c1f5c7a6d there are still some bugs are not being resolve.

1. The `<a> href` links are still not resolved.
e.g. `./assets/logo.svg` still linking to `https://unjs.io/assets/logo.svg`

2. If the URL starting with `src="asset` instead of `src="./asset/"`, it cannot replace with the regex `/src="\./g`

Sample: https://unjs.io/webpackbar

Hope to continue the discussion in PR #14 possible.
